// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pehbbwjbuhxhscbdtnjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlaGJid2pidWh4aHNjYmR0bmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTczNzYsImV4cCI6MjA2ODgzMzM3Nn0.5LDIf_3UsvSwgVmTSKhZz2PKTOmdIOGfKhxsPjNMAWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});